/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package abblcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class abb_irb140joint_plan implements lcm.lcm.LCMEncodable
{
    public long utime;
    public long n_cmd_times;
    public abblcm.abb_irb140joints joint_cmd[];
 
    public abb_irb140joint_plan()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9bb7669ecfca359cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(abblcm.abb_irb140joint_plan.class))
            return 0L;
 
        classes.add(abblcm.abb_irb140joint_plan.class);
        long hash = LCM_FINGERPRINT_BASE
             + abblcm.abb_irb140joints._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeLong(this.n_cmd_times); 
 
        for (int a = 0; a < this.n_cmd_times; a++) {
            this.joint_cmd[a]._encodeRecursive(outs); 
        }
 
    }
 
    public abb_irb140joint_plan(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public abb_irb140joint_plan(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static abblcm.abb_irb140joint_plan _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        abblcm.abb_irb140joint_plan o = new abblcm.abb_irb140joint_plan();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.n_cmd_times = ins.readLong();
 
        this.joint_cmd = new abblcm.abb_irb140joints[(int) n_cmd_times];
        for (int a = 0; a < this.n_cmd_times; a++) {
            this.joint_cmd[a] = abblcm.abb_irb140joints._decodeRecursiveFactory(ins);
        }
 
    }
 
    public abblcm.abb_irb140joint_plan copy()
    {
        abblcm.abb_irb140joint_plan outobj = new abblcm.abb_irb140joint_plan();
        outobj.utime = this.utime;
 
        outobj.n_cmd_times = this.n_cmd_times;
 
        outobj.joint_cmd = new abblcm.abb_irb140joints[(int) n_cmd_times];
        for (int a = 0; a < this.n_cmd_times; a++) {
            outobj.joint_cmd[a] = this.joint_cmd[a].copy();
        }
 
        return outobj;
    }
 
}

