/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package abblcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class abb_irb140ftsensor implements lcm.lcm.LCMEncodable
{
    public long utime;
    public float hand_force[];
    public float hand_torque[];
 
    public abb_irb140ftsensor()
    {
        hand_force = new float[3];
        hand_torque = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4383ed648b51f22aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(abblcm.abb_irb140ftsensor.class))
            return 0L;
 
        classes.add(abblcm.abb_irb140ftsensor.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hand_force[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.hand_torque[a]); 
        }
 
    }
 
    public abb_irb140ftsensor(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public abb_irb140ftsensor(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static abblcm.abb_irb140ftsensor _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        abblcm.abb_irb140ftsensor o = new abblcm.abb_irb140ftsensor();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.hand_force = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hand_force[a] = ins.readFloat();
        }
 
        this.hand_torque = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.hand_torque[a] = ins.readFloat();
        }
 
    }
 
    public abblcm.abb_irb140ftsensor copy()
    {
        abblcm.abb_irb140ftsensor outobj = new abblcm.abb_irb140ftsensor();
        outobj.utime = this.utime;
 
        outobj.hand_force = new float[(int) 3];
        System.arraycopy(this.hand_force, 0, outobj.hand_force, 0, 3); 
        outobj.hand_torque = new float[(int) 3];
        System.arraycopy(this.hand_torque, 0, outobj.hand_torque, 0, 3); 
        return outobj;
    }
 
}

