"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class abb_irb140ftsensor(object):
    __slots__ = ["utime", "hand_force", "hand_torque"]

    def __init__(self):
        self.utime = 0
        self.hand_force = [ 0.0 for dim0 in range(3) ]
        self.hand_torque = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(abb_irb140ftsensor._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3f', *self.hand_force[:3]))
        buf.write(struct.pack('>3f', *self.hand_torque[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != abb_irb140ftsensor._get_packed_fingerprint():
            raise ValueError("Decode error")
        return abb_irb140ftsensor._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = abb_irb140ftsensor()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.hand_force = struct.unpack('>3f', buf.read(12))
        self.hand_torque = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if abb_irb140ftsensor in parents: return 0
        tmphash = (0x4383ed648b51f22a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if abb_irb140ftsensor._packed_fingerprint is None:
            abb_irb140ftsensor._packed_fingerprint = struct.pack(">Q", abb_irb140ftsensor._get_hash_recursive([]))
        return abb_irb140ftsensor._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

