/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package abblcm;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class abb_irb140cartesian implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double pos[];
    public double quat[];
 
    public abb_irb140cartesian()
    {
        pos = new double[3];
        quat = new double[4];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9ba71fd48cb530d2L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(abblcm.abb_irb140cartesian.class))
            return 0L;
 
        classes.add(abblcm.abb_irb140cartesian.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.pos[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeDouble(this.quat[a]); 
        }
 
    }
 
    public abb_irb140cartesian(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public abb_irb140cartesian(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static abblcm.abb_irb140cartesian _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        abblcm.abb_irb140cartesian o = new abblcm.abb_irb140cartesian();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.pos = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.pos[a] = ins.readDouble();
        }
 
        this.quat = new double[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.quat[a] = ins.readDouble();
        }
 
    }
 
    public abblcm.abb_irb140cartesian copy()
    {
        abblcm.abb_irb140cartesian outobj = new abblcm.abb_irb140cartesian();
        outobj.utime = this.utime;
 
        outobj.pos = new double[(int) 3];
        System.arraycopy(this.pos, 0, outobj.pos, 0, 3); 
        outobj.quat = new double[(int) 4];
        System.arraycopy(this.quat, 0, outobj.quat, 0, 4); 
        return outobj;
    }
 
}

