"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class abb_irb140pos(object):
    __slots__ = ["timestamp", "Joint1", "Joint2", "Joint3", "Joint4", "Joint5", "Joint6"]

    def __init__(self):
        self.timestamp = 0
        self.Joint1 = 0.0
        self.Joint2 = 0.0
        self.Joint3 = 0.0
        self.Joint4 = 0.0
        self.Joint5 = 0.0
        self.Joint6 = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(abb_irb140pos._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdddddd", self.timestamp, self.Joint1, self.Joint2, self.Joint3, self.Joint4, self.Joint5, self.Joint6))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != abb_irb140pos._get_packed_fingerprint():
            raise ValueError("Decode error")
        return abb_irb140pos._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = abb_irb140pos()
        self.timestamp, self.Joint1, self.Joint2, self.Joint3, self.Joint4, self.Joint5, self.Joint6 = struct.unpack(">qdddddd", buf.read(56))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if abb_irb140pos in parents: return 0
        tmphash = (0x4374c051f0450483) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if abb_irb140pos._packed_fingerprint is None:
            abb_irb140pos._packed_fingerprint = struct.pack(">Q", abb_irb140pos._get_hash_recursive([]))
        return abb_irb140pos._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

