"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import abblcm.abb_irb140joints

class abb_irb140joint_plan(object):
    __slots__ = ["utime", "n_cmd_times", "joint_cmd"]

    def __init__(self):
        self.utime = 0
        self.n_cmd_times = 0
        self.joint_cmd = []

    def encode(self):
        buf = BytesIO()
        buf.write(abb_irb140joint_plan._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qq", self.utime, self.n_cmd_times))
        for i0 in range(self.n_cmd_times):
            assert self.joint_cmd[i0]._get_packed_fingerprint() == abblcm.abb_irb140joints._get_packed_fingerprint()
            self.joint_cmd[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != abb_irb140joint_plan._get_packed_fingerprint():
            raise ValueError("Decode error")
        return abb_irb140joint_plan._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = abb_irb140joint_plan()
        self.utime, self.n_cmd_times = struct.unpack(">qq", buf.read(16))
        self.joint_cmd = []
        for i0 in range(self.n_cmd_times):
            self.joint_cmd.append(abblcm.abb_irb140joints._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if abb_irb140joint_plan in parents: return 0
        newparents = parents + [abb_irb140joint_plan]
        tmphash = (0x9bb7669ecfca359c+ abblcm.abb_irb140joints._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if abb_irb140joint_plan._packed_fingerprint is None:
            abb_irb140joint_plan._packed_fingerprint = struct.pack(">Q", abb_irb140joint_plan._get_hash_recursive([]))
        return abb_irb140joint_plan._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

