"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class abb_irb140cartesian(object):
    __slots__ = ["timestamp", "pos", "quat"]

    def __init__(self):
        self.timestamp = 0
        self.pos = [ 0.0 for dim0 in range(3) ]
        self.quat = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(abb_irb140cartesian._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>3d', *self.pos[:3]))
        buf.write(struct.pack('>4d', *self.quat[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != abb_irb140cartesian._get_packed_fingerprint():
            raise ValueError("Decode error")
        return abb_irb140cartesian._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = abb_irb140cartesian()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.pos = struct.unpack('>3d', buf.read(24))
        self.quat = struct.unpack('>4d', buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if abb_irb140cartesian in parents: return 0
        tmphash = (0xf02090d33f52b0f5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if abb_irb140cartesian._packed_fingerprint is None:
            abb_irb140cartesian._packed_fingerprint = struct.pack(">Q", abb_irb140cartesian._get_hash_recursive([]))
        return abb_irb140cartesian._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

